{% set version = "0.9.4" %}

package:
  name: pydoe
  version: {{ version }}

source:
  fn: pyDOE-{{ version }}.zip
  url: https://pypi.org/packages/source/p/pyDOE/pydoe-{{ version }}.tar.gz
  sha1: dea8d81c0ddf62fee0f80386092e890ecc688516

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  number: 0

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python
    - scipy >=0.13
    - numpy >=1.8

test:
  imports:
    - pyDOE

about:
  home: https://github.com/tisimst/pyDOE
  license: BSD 3-Clause
  license_file: LICENSE
  summary: Design of experiments for Python
  description: The pyDOE package is designed to help the scientist, engineer, statistician, etc., to construct appropriate experimental designs.

extra:
  recipe-maintainers:
    - melund
