{% set version = "1.0.1" %}
{% set python_min = "3.11" %}

package:
  name: pydoe
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pydoe/pydoe-{{ version }}.tar.gz
  sha256: c487ca80154d59a9812c9f1227dab60dfc3c47cd691f55c55322b7b1b1450b5a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed .
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling >=1.26
    - hatch-vcs

  run:
    - python >={{ python_min }}
    - scipy >=1.15.3
    - numpy >=2.2.6

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyDOE

about:
  home: https://github.com/tisimst/pyDOE
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Design of experiments for Python
  description: The pyDOE package is designed to help the scientist, engineer, statistician, etc., to construct appropriate experimental designs.

extra:
  recipe-maintainers:
    - saudzahirr
    - melund
    - laraibg786
